---
- hosts: all
  become: true
  tasks:
    - name: Ensure middleware groups exists
      group:
        name: "{{ item }}"
        state: present
      with_items:
         - middlewareDev
         - middlewareSvt
         - middlewareUat
         - middlewareProd
    - script: ./mkdir.sh dev

